name: 'deploy to aws s3'
description: 'deployed static website via s3'
inputs: 
  bucket: 
    description: 'The s3 bucket name'
    required: true
  bucket-region: 
    description: 'The region of the s3 bucket'
    default: 'us-east-1'
  dist-folder: 
    description: 'Folder containing the deployable files'
    default: 'true'
outputs:
  website-url:
    description: 's3 url'
runs:
  using: 'node20'
  main: 'main.js' 
      